Add preprod and prod to routing
ONSdigital/ras-maintenance-page pull request #9
Opened 2019-08-13 14:06 UTC by mfcrocker

# Motivation and Context
We should be doing re-routing for deployments by script to avoid mistakes

# What has changed
Used an existing script that does the same thing

# How to test?
Use this next time we do a preprod deployment

2019-08-13 14:07 UTC, insacuri requested changes

2019-08-13 14:07 UTC, insacuri commented on deploy.sh
>    echo "Unknown environment, currently script only supports: $DEV_ENVIRONMENT"
The fail case needs to be updated

2019-08-13 14:09 UTC, insacuri approved these changes

2019-08-13 15:18 UTC, gavinleeedwards requested changes

2019-08-13 15:18 UTC, gavinleeedwards commented on deploy.sh
>  SIT_ENVIRONMENT="sit"
The only dev environments that are used are ci and concourse-latest.  But in either case, the maintenance page isn't deployed into those environments so they should be removed, unless there are plans to deploy the maintenance page into them.

2019-08-13 15:18 UTC, gavinleeedwards commented on deploy.sh
> +  echo "Unknown environment, currently script only supports: $DEV_ENVIRONMENT, $SIT_ENVIRONMENT, $PREPROD_ENVIRONMENT and $PROD_ENVIRONMENT"
The script doesn't currently support dev environments so it could just be changed to preprod/prod.

2019-08-13 15:18 UTC, gavinleeedwards commented on deploy.sh
> +  DOMAIN="apps.prod.cf5.onsclofo.uk"
Should this domain be there or is it a secret?  I'm not sure.

2019-08-13 15:25 UTC, mfcrocker commented on deploy.sh
> +  DOMAIN="apps.prod.cf5.onsclofo.uk"
Am checking with TL :)

2019-08-15 14:50 UTC, necrophonic approved these changes

2019-08-15 14:50 UTC, necrophonic commented on deploy.sh
> +  DOMAIN="apps.prod.cf5.onsclofo.uk"
Checked with IA - seems fine to us but we're going to enter things like this onto a page Dan is putting together to ensure we've captured that they've been discussed and agreed

2019-09-05 15:47 UTC, merged